#!/bin/sh
#  Shell script to load database table metadata into a TAP server.
#  Written by: Tom Hicks. 9/5/2019.
#  Last Modified: Initial creation.
#
progname=`basename $0`

TABLE=$1
SCHEMA=${2:-sia}

if [ $# -lt 1 -o "$1" = "-h" -o "$1" = "--help" ]; then
  echo "Usage: $0 table-name [schema-name]"
  exit 1
fi

java -cp dist/dals.jar:lib/FITSWCS-2.4+dev.jar:lib/cadcDALI.jar:lib/cadcLog.jar:\
lib/cadcRegistryClient.jar:lib/cadcTAP.jar:lib/cadcUWS.jar:lib/cadcUtil.jar:lib/cadcVOSI.jar:\
lib/cds-savot-2.6.jar:lib/cds-savot-3.0.jar:lib/commons-cli-1.3.jar:lib/commons-dbcp-1.4.jar:\
lib/commons-fileupload.jar:lib/commons-logging.jar:lib/commons-pool-1.6.jar:lib/horizon-data.jar:\
lib/javacsv.jar:lib/javax.servlet.jar:lib/jdom2.jar:lib/jsqlparser.jar:lib/junit-4.8.1.jar:\
lib/kxml2-2.3.0.jar:lib/log4j.jar:lib/nekohtml.jar:lib/nom-tam-fits-1.11.jar:\
lib/org.restlet.ext.fileupload.jar:lib/org.restlet.ext.servlet.jar:lib/org.restlet.jar:\
lib/postgresql-jdbc.jar:lib/spring.jar:lib/texttable.jar:lib/xerces.jar:lib/xmlParserAPIs-2.6.1.jar\
  dalserver.tap.TapSchema -d file:config/tap-load.properties -s ${SCHEMA} -a ${TABLE}
